<a href="https://colab.research.google.com/github/kyleorgel/sustainability-reports/blob/main/Upload_New_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Airtable Data Simulation

To interact with Airtable, you would typically use an API client or a library. For this demonstration, I'll create a sample pandas DataFrame that mimics the structure of data you might fetch from Airtable, including the columns you specified.

In [2]:
import pandas as pd

# Simulate Airtable data
data = {
    'Company': ['Company A', 'Company B', 'Company C'],
    'ticker': ['CMPSA', 'CMPSB', 'CMPSC'],
    'report name': ['Annual Report 2023', 'Q3 Earnings', 'Sustainability Report'],
    'report year': [2023, 2024, 2022],
    'sector': ['Technology', 'Finance', 'Manufacturing'],
    'pdf of the report URL': [
        'https://example.com/report_a.pdf',
        'https://example.com/report_b.pdf',
        'https://example.com/report_c.pdf'
    ],
    'other_column': ['value1', 'value2', 'value3'] # Some other columns that might exist
}

df = pd.DataFrame(data)

print("Original DataFrame:")
display(df)

Original DataFrame:

,Company,ticker,report name,report year,sector,pdf of the report URL,other_column
0,Company A,CMPSA,Annual Report 2023,2023,Technology,https://example.com/report_a.pdf,value1
1,Company B,CMPSB,Q3 Earnings,2024,Finance,https://example.com/report_b.pdf,value2
2,Company C,CMPSC,Sustainability Report,2022,Manufacturing,https://example.com/report_c.pdf,value3

## Selecting and Reordering Columns

Now, let's select the specific columns you requested and display them in your desired order.

In [4]:
desired_columns = [
    'Company',
    'ticker',
    'report name',
    'report year',
    'sector',
    'pdf of the report URL'
]

# Select and reorder the columns
df_filtered = df[desired_columns]

print("Filtered and reordered DataFrame:")
display(df_filtered)

Filtered and reordered DataFrame:

,Company,ticker,report name,report year,sector,pdf of the report URL
0,Company A,CMPSA,Annual Report 2023,2023,Technology,https://example.com/report_a.pdf
1,Company B,CMPSB,Q3 Earnings,2024,Finance,https://example.com/report_b.pdf
2,Company C,CMPSC,Sustainability Report,2022,Manufacturing,https://example.com/report_c.pdf

## Incorporating a Company Logo

Adding a company logo to the 'top header' of a Colab notebook usually refers to custom HTML/CSS styling within a markdown cell, or in some external web application where the notebook content is embedded. Colab notebooks themselves don't have a direct 'top header' that can be modified via Python code or markdown in the same way a webpage does.

However, if you wanted to display the logo *within* the notebook content (e.g., at the top of your report or analysis), you could use a markdown cell with an image tag. Replace `path/to/your/logo.png` with the actual path or URL of your logo image. The `width` and `height` attributes can be adjusted for sizing.

```markdown
<img src="/content/OrgelHD.ai" alt="Your Company Logo" width="150" height="auto">
```

**Note:** If `OrgelHD.ai` is an Adobe Illustrator file, it cannot be directly displayed as an image in HTML like a `.png`, `.jpg`, or `.svg` file. You would need to convert it to a web-compatible image format first (e.g., PNG, JPEG, or SVG if it's vector-based) and then reference that converted file in the `src` attribute.